FROM cypress/base:16.16.0

RUN mkdir -p /app

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

RUN npm run test

COPY . .

RUN npx cypress verify

CMD ["npm", "run", "e2e:ci"]
