version: "3.9"  # optional since v1.27.0
services:
  api:
    image: backend
    build: ./server
    ports:
      - "7009:80"
  webapp:
    image: frontend
    build: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client/cypress:/app/cypress
      - ./client/.nyc_output:/app/.nyc_output
      - ./client/coverage:/app/coverage
      - ./client/results:/app/results
