version: "3.9"  # optional since v1.27.0
services:
  api:
    image: backend
    build: ./server
  webapp:
    image: frontend-e2e
    build:
      context: ./client
      dockerfile: Dockerfile_ci
    environment:
      - AUTH0_USERNAME
      - AUTH0_PASSWORD
      - AUTH0_DOMAIN
      - AUTH0_AUDIENCE
      - AUTH0_SCOPE
      - AUTH0_CLIENTID
      - AUTH0_CLIENT_SECRET
    volumes:
      - ./client/cypress:/app/cypress
      - ./client/.nyc_output:/app/.nyc_output
      - ./client/coverage:/app/coverage
      - ./client/results:/app/results
      - ./client/coverage-jest:/app/coverage-jest
