version: "3.9"  # optional since v1.27.0
services:
  webapp:
    image: frontend
    build: ./client
    ports:
      - "3000:3000"
  e2e:
    image: cypress
    build: ./e2e
    depends_on:
      - webapp
    environment:
      - CYPRESS_baseUrl=http://webapp:3000
    command: npx cypress run
    volumes:
      - ./client/cypress:/app/cypress
      - ./client/cypress.config.ts:/app/cypress.config.ts
      - ./client/tsconfig.json:/app/tsconfig.json
