version: "3.9"  # optional since v1.27.0
services:
  api:
    image: backend
    build: ./server
  webapp:
    image: frontend-e2e
    build:
      context: ./client
      dockerfile: Dockerfile_ci
    volumes:
      - ./client/cypress:/app/cypress
      - ./client/.nyc_output:/app/.nyc_output
      - ./client/coverage:/app/coverage
      - ./client/results:/app/results
