version: "3.9"  # optional since v1.27.0
services:
  api:
    image: backend
    build: ./server
    ports:
      - "7009:80"
  webapp:
    image: frontend
    build: ./client
    depends_on:
      - api
    ports:
      - "4200:4200"
